### ISSUE TITLE
My <hr> Lines Disappear at Larger Screen Sizes

### ISSUE THREAD

**Issue by LauraWilson040** [LauraWilson040/modularity-mindfulness#1]
- Before with my old grid, the hr lines would switch to be vertical.
- The hr lines now disappear at larger screen sizes.
- Is this a grid issue?

@mackenzierose @hellachella

<img width="612" alt="Screen Shot 2020-09-28 at 4 05 02 PM" src="https://user-images.githubusercontent.com/55108851/94480717-b3ef4980-01a4-11eb-8594-a8cfb622be26.png">
<img width="1680" alt="Screen Shot 2020-09-28 at 4 05 05 PM" src="https://user-images.githubusercontent.com/55108851/94480726-b5b90d00-01a4-11eb-87a4-d96bdcbafd12.png">

**Comment by MacKenzieRose** [comment]
The `<hr>` visually disappearing might very well be a grid incompatibility thing. The good news is that you can accomplish this assignment without problems, without using horizontal rules at all. Instead, try a `border-bottom` and `border-top` where you need those gray lines 😸 

Let me know if that helps!
