### ISSUE TITLE
Issue with Column Gaps

### ISSUE THREAD

**Issue by LauraWilson040** [LauraWilson040/modularity-mindfulness#2]
- The column gap I applied appears on both Chrome and Firefox, but not on Markbot. Is this a glitch? Or did I just apply the gap to the wrong selector?
![Screen Shot 2020-09-29 at 5 05 31 PM](https://user-images.githubusercontent.com/55108851/94619070-3c8be980-027a-11eb-9d62-f19b64037a4d.png)
<img width="1680" alt="Screen Shot 2020-09-29 at 5 14 33 PM" src="https://user-images.githubusercontent.com/55108851/94619105-49a8d880-027a-11eb-8941-0319c2c645fc.png">

@hellachella @mackenzierose

**Comment by hellachella** [comment]
Taking a look!

**Comment by MacKenzieRose** [comment]
I think this is an issue stemming from how the grid was set up; second issue tag here: [https://github.com/LauraWilson040/modularity-mindfulness/issues/3]

**Comment by hellachella** [comment]
1. Change the divs inside of your section to articles. It's more specific and better for screen readers. 
2. you have your gap in the right place but once you have changed the `divs` inside of your `section` into `articles`, include this: 
```
article {
  display: flex;
  justify-content: space-between; /*This should solve it*/
  flex-direction: column;
}
```
